name: Release - Canary

on:
  pull_request:
    types: [labeled]
    branches:
      - main
jobs:
  release:
    if: contains(github.event.pull_request.labels.*.name, 'release canary')
    name: Build & Publish a canary release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps (with cache)
        run: bun install

      - name: Check packages for common errors
        run: bun turbo --filter "./packages/*" build

      - name: Bump version to canary
        run: bun run .github/canary-version.ts

      - name: Authenticate to npm and publish
        run: |
          for dir in packages/*/; do
          if [ "$dir" != "packages/config/" ]; then
              echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > "$dir/.npmrc"
              cd "$dir" && npm publish --access public --tag canary
            fi  
          done

      - name: Create a new comment notifying of the new canary version
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get package version
            const fs = require("fs");
            let text = 'A new canary is available for testing. You can install this latest build in your project with:\n\n```sh\n'

            const pkgJsonPaths = fs
              .readdirSync("packages")
              .filter((dir) => dir !== "config")
              .map((dir) => `packages/${dir}/package.json`);

            for (const pkgJsonPath of pkgJsonPaths) {
              const packageJson = JSON.parse(fs.readFileSync(pkgJsonPath));
              const version = packageJson.version;
              text += `bun add ${packageJson.name}@${version}\n`
            }
            text += '```\n\n'

            // Create a comment on the PR with the new canary version
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: text,
            })

            // Remove the label
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              name: 'release canary',
            });
